// A regular array containing 3 items...
let regularArray = ["name", "phone", "address"];

// Example of the kind of array I had containing items with commas...
let myArray = ["name, ", "phone,", "address,"];

// Mapping through myArray in my React component...
myArray.map((item) => <h1>item</h1>);
// Output assuming each item has a margin-x...
// name, phone, address,

// To get rid of the trailing comma...
// Using splice method in javascript

// Get the last item in the array...
let lastItem = myArray[myArray.length - 1];
// lastItem = "address,"

// Remove the last letter of the string...
lastItem = lastItem.substring(0, lastItem.length - 1);
// lastItem = "address"

// Replace with the last item in myArray...
myArray.splice(-1, 1, lastItem);

myArray.map((item) => <h1>item</h1>);
// Output assuming each item has a margin-x...
// name, phone, address
